pipeline {
	agent any
	stages {

		stage('Build') {
			steps {

				script {
					try {
						sh 'curl  --request GET http://c9b6b6f1.ngrok.io/start/'
					} catch (Exception e) {
						echo 'Check the host...'
					}
				}
				sh 'mvn clean package'
				archiveArtifacts 'cbs-server/target/*.war'
			}
		}


		stage('Tests') {
			steps {
				sh 'mvn clean test -Dmaven.test.failure.ignore=true'
				junit '**/target/surefire-reports/TEST-*.xml'
			}
		}

		stage('Deploy') {
			steps {
				script {
					try {
						sh 'curl  --request GET http://c9b6b6f1.ngrok.io/warn/'
					} catch (Exception e) {
						echo 'Check the host...'
					}
				}
				input 'Are you sure?'
				echo 'Deploying...'
				build job: 'cbs-deployment'
			}
		}

		stage('Release') {
			steps {
				echo 'Releasing...'
			}
		}

		stage('Deploy @ Prod') {
			steps {
				echo 'Deploying @ Prod...'
			}
		}
	}

	post {
		always {
			echo 'I have finished.'
			try {
				sh 'curl  --request GET http://c9b6b6f1.ngrok.io/xmas/'
			} catch (Exception e) {
				echo 'Check the host...'
			}
		}
		success {
			echo 'Job succeeeded!'
			script {
				try {
					sh 'curl  --request GET http://c9b6b6f1.ngrok.io/ok/'
				} catch (Exception e) {
					echo 'Check the host...'
				}
			}
		}
		unstable {
			echo 'I am unstable :/'
		}
		failure {
			echo 'I failed :('
			script {
				try {
					sh 'curl --request GET http://c9b6b6f1.ngrok.io/nok/'
				} catch (Exception e) {
					echo 'Check the host...'
				}
			}
		}
		changed {
			echo 'Things were different before...'
		}
	}
}